name: flutter_template
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.0.0
  flutter: ^3.13.1

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.8 # https://pub.dev/packages/animations
  async: ^2.11.0 # https://pub.dev/packages/async  参考記事: https://zenn.dev/8rine23/articles/5772f7d81144bd
  app_settings: ^5.1.1 # https://pub.dev/packages/app_settings
  auto_size_text: ^3.0.0 # https://pub.dev/packages/auto_size_text
  cupertino_icons: 
  collection: ^1.17.2 # https://pub.dev/packages/collection  参考記事: https://zenn.dev/ashphy/articles/1bdfc8e8084fc2
  flutter_native_splash: ^2.3.2 # https://pub.dev/packages/flutter_native_splash
  go_router: ^10.1.1 # https://pub.dev/packages/go_router
  riverpod_annotation: ^2.1.5 # https://pub.dev/packages/riverpod_annotation
  freezed_annotation: ^2.4.1 # https://pub.dev/packages/freezed_annotation
  json_annotation: ^4.8.1 # https://pub.dev/packages/json_annotation
  hooks_riverpod: ^2.4.0 # https://pub.dev/packages/hooks_riverpod
  flutter_hooks: ^0.20.1 # https://pub.dev/packages/flutter_hooks
  device_info_plus: ^9.0.3 # https://pub.dev/packages/device_info_plus/install
  dio: ^5.3.2 # https://pub.dev/packages/dio
  dotted_line: ^3.2.2 # https://pub.dev/packages/dotted_line
  retrofit: ^4.0.1 # https://pub.dev/packages/retrofit
  logger: ^2.0.2 # https://pub.dev/packages/logger
  package_info_plus: ^4.1.0 # https://pub.dev/packages/package_info_plus
  permission_handler: ^11.0.1 # https://pub.dev/packages/permission_handler
  shared_preferences: ^2.2.1 # https://pub.dev/packages/shared_preferences
  share_plus: ^7.1.0 # https://pub.dev/packages/share_plus
  scrollable_positioned_list: ^0.3.8 # https://pub-web.flutter-io.cn/packages/scrollable_positioned_list
  flutter_secure_storage: ^9.0.0 # https://pub.dev/packages/flutter_secure_storage
  flutter_svg: ^2.0.7 # https://pub.dev/packages/flutter_svg

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.24.0+1 # https://pub.dev/packages/pedantic_mono
  flutter_launcher_icons: "^0.13.1" # https://pub.dev/packages/flutter_launcher_icons
  go_router_builder: ^2.3.0 # https://pub.dev/packages/go_router_builder
  build_runner: ^2.4.6 # https://pub.dev/packages/build_runner
  riverpod_generator: ^2.3.2 # https://pub.dev/packages/riverpod_generator
  custom_lint: ^0.5.3 # riverpod_lintを使うために入っている https://pub.dev/packages/custom_lint
  riverpod_lint: ^2.0.4 # https://pub.dev/packages/riverpod_lint
  json_serializable: ^6.7.1 # https://pub.dev/packages/json_serializable
  freezed: ^2.4.1 # https://pub.dev/packages/freezed
  retrofit_generator: ^7.0.8 # https://pub.dev/packages/retrofit_generator

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/svgs/
    - assets/splashes/
    
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Black.ttf
          weight: 900
        - asset: assets/fonts/NotoSansJP-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansJP-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansJP-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansJP-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansJP-Thin.ttf
          weight: 100

flutter_launcher_icons:
  # flutter pub run flutter_launcher_icons:main
  android: true
  ios: true
  image_path: "assets/splashes/template.png"
  adaptive_icon_background: "#eeeeee"
  adaptive_icon_foreground: "assets/splashes/template.png"
  web:
    generate: true
    image_path: "assets/splashes/template.png"
    background_color: "#eeeeee"
    theme_color: "#eeeeee"
  windows:
    generate: true
    image_path: "assets/splashes/template.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/splashes/template.png"

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  # flutter pub run flutter_native_splash:remove
  color: "#eeeeee"
  image: "assets/splashes/template.png"
  color_dark: "#262626"
  image_dark: "assets/splashes/template.png"
  branding: "assets/splashes/branding.png"
  branding_mode: bottom

  # Android12以上はAndroidOS側でアプリアイコンをスプラッシュ表示してしまうので以下の通り設定が必要
  android_12:
    image: "assets/splashes/template.png"
    icon_background_color: "#eeeeee"
    image_dark: "assets/splashes/template.png"
    icon_background_color_dark: "#262626"
    branding: "assets/splashes/branding.png"
    branding_mode: bottom
