name: flutter_template
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.2
  go_router: ^10.1.1
  flutter_riverpod: ^2.3.10
  riverpod_annotation: ^2.1.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  go_router_builder: ^2.3.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.1
  custom_lint: ^0.5.3
  riverpod_lint: ^2.0.3
  json_serializable: ^6.7.1
  freezed: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
    # flutter pub run flutter_launcher_icons:main
  android: true
  ios: true
  image_path: 'assets/images/template.png'
  adaptive_icon_background: '#eeeeee'
  adaptive_icon_foreground: 'assets/images/template.png'
  web:
    generate: true
    image_path: 'assets/images/template.png'
    background_color: '#eeeeee'
    theme_color: '#eeeeee'
  windows:
    generate: true
    image_path: 'assets/images/template.png'
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: 'assets/images/template.png'

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  # flutter pub run flutter_native_splash:remove
  color: '#eeeeee'
  image: 'assets/images/template.png'
  color_dark: '#262626'
  image_dark: 'assets/images/template.png'

  # Android12以上はAndroidOS側でアプリアイコンをスプラッシュ表示してしまうので以下の通り設定が必要
  android_12:
    image: 'assets/images/template.png'
    icon_background_color: '#eeeeee'
    image_dark: 'assets/images/template.png'
    icon_background_color_dark: '#262626'